---
- name: building the docker images
  hosts: all
  become: true
  tasks:
    - name: copy the file to remote server
      shell: scp -r /var/lib/jenkins/workspace/ansible-pipeline/ root@52.55.181.126~:/project/
    - name: remove the present image 
      docker_image:
        name: mysql
        state: absent
    - name: pull the docker image from docker hub
      docker_image:
        name: mysql
        source: pull
        state: present  
    - name: run the MySQL image 
      docker_container:
        name: mydb
        image: mysql
        state: started  
        restart_policy: always  
        ports:
          - "7070:3306"
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
    - name: install webserver
      docker_container:
        name: webserver
        image: tomee
        state: started
        ports:
          - "6060:8080"
