---
- name: install docker on nodes
  hosts: node
  tasks:
     - name: install docker and integrate docker with ansible
       shell: "{{item}}"
       with_items:
        - curl -fsSL https://get.docker.com -o install-docker.sh
        - sh install-docker.sh
     - name: install pip3
       apt:
        name: python3-pip
        state: present
        update_cache: yes
     - name: integrate docker
       apt:
         name: python3-docker
...
